### ISSUE TITLE
Periscope caching

### ISSUE THREAD

**Issue by 3osman** [3osman/live-api#7]
Turns out for periscope to work, you have to do the same search call first on their website (from a browser), so it caches it, and then do it in Reemote API.

If you call from Reemote API directly, no results return, as the call doesnt wait for the results to load in Javascript.

Solution hint: make a call from our API to periscope with javascript enabled (not sure if it is possible from a server side).

**Comment by 3osman** [comment]
@leolanzinger any idea?

**Comment by leolanzinger** [comment]
hmmm im not sure i understand what "with javascript enabled" means ;)
